### ISSUE TITLE
Broken npm install - code: 'SELF_SIGNED_CERT_IN_CHAIN'

### ISSUE THREAD

**Issue by OSnuszka** [mdn/mdn-http-observatory#126]
### What information was incorrect, unhelpful, or incomplete?

My bundle after npm install against newest version of http-observatory/or current main branch -  do not longer build correctly.

It return error stack trace contains:

`npm error command failed
npm error command sh -c node index.js
npm error Downloading from URL https://ccadb-public.secure.force.com/mozilla/PublicAllIntermediateCertsWithPEMCSV
npm error node:internal/process/promises:391
npm error     triggerUncaughtException(err, true /* fromPromise */);`

`npm error   code: 'SELF_SIGNED_CERT_IN_CHAIN',`

node -v
v20.18.0
npm -v
10.8.2

I already fixed that by force install version of http-observatory `1.3.3`

### What did you expect to see?

Bundle should install correctly

**Comment by argl** [comment]
Thanks for reporting, will look into it.

**Comment by argl** [comment]
Can you please try again? An updated version just landed on npm. 

Based on your report, it seems like the `node_extra_ca_certs_mozilla_bundle` had problems downloading files from ccadb. It does so at npm install time. Can you check if you can download `https://ccadb-public.secure.force.com/mozilla/PublicAllIntermediateCertsWithPEMCSV` manually?

**Comment by OSnuszka** [comment]
@argl thank you it helps, I updated my runner in CI/CD
