### ISSUE TITLE
Deploy by docker-compose

### ISSUE THREAD

**Issue by zanderhan** [mdn/mdn-http-observatory#144]
### What information was incorrect, unhelpful, or incomplete?

How do I deploy through docker-compose?
Your documentation doesn't say anything, especially about database deployment.

①I tried to write a docker-compose.yml file that as follows:
![image](https://github.com/user-attachments/assets/68ebec9c-112f-485d-bdd1-8094897b12be)

②Then execute: docker-compose up --build

③When access: http://ip:8080/
I can see "Welcome to the MDN Observatory!"

④When execute: curl -X POST "http://IP:8080/api/v2/scan?host=example.com"
It return: {"error":"error-unknown","message":"connect ECONNREFUSED 127.0.0.1:5432"}

⑤This should be a problem of my database configuration.

### What did you expect to see?

The official docker-compolse.yml file

**Comment by argl** [comment]
Hi, thank you for reporting an issue. We do not actively support docker-compose, but this looks like a connection issue to the database container.

**Comment by zanderhan** [comment]
Thank you for your reply. How do I configure the database?
