### ISSUE TITLE
Allow API with 401/403 Status Code to be Scanned

### ISSUE THREAD

**Issue by azfar26** [mdn/mdn-http-observatory#42]
### What information was incorrect, unhelpful, or incomplete?

Hello MDN team,

With the previous Observatory (https://observatory.mozilla.org/), I can scan my API that returned `401 Unauthorized` status code by default. Secure response headers are still returned by the API and Observatory gave a grade of A+.

With the new Observatory (https://developer.mozilla.org/en-US/observatory), sites that did not respond with a 2xx HTTP status code are not allowed to be scanned.

### What did you expect to see?

I read the [FAQ section](https://developer.mozilla.org/en-US/observatory/docs/faq#can-i-scan-non-websites-such-as-api-endpoints-) here, although HTTP Observatory is designed for scanning website, it can be used for API endpoints as well.

I'm expecting my API to be allowed to scan, just like in the previous Observatory. To narrow down the non-2xx status code, you can allow only `401 Unauthorized` and `403 Forbidden` status codes - since these are the typical status codes returned by API with unauthorized access.

### Do you have anything more you want to share?

![image](https://github.com/user-attachments/assets/ad8e8418-adc9-4b57-91c8-db9f9e098605)

**Comment by argl** [comment]
Hi, could you check again? Some changes have been deployed recently.

**Comment by azfar26** [comment]
@argl I'm able to scan my API now. Thanks for the fix! 👍🏼
