### ISSUE TITLE
Public API Docs

### ISSUE THREAD

**Issue by chris48s** [mdn/mdn-http-observatory#43]
### What information was incorrect, unhelpful, or incomplete?

The old Mozilla Observatory site had an "API Documentation" menu item, which linked to https://github.com/mozilla/http-observatory/blob/main/httpobs/docs/api.md

The new MDN HTTP Observatory doesn't explicitly link to any public API docs. https://developer.mozilla.org/en-US/blog/mdn-http-observatory-launch/ makes some references to an API and it does appear to be possible to call a URL like https://observatory-api.mdn.mozilla.net/api/v2/analyze?host=shields.io but it is unclear if this is a public API we are allowed to use with some expectation of stability or an internal API.

### What did you expect to see?

Either:

- Documentation on how to access MDN HTTP Observatory though a public API or
- Clear statement that this is not available.

### Do you have any supporting links, references, or citations?

- https://observatory.mozilla.org/
- https://github.com/mozilla/http-observatory/blob/main/httpobs/docs/api.md
- https://developer.mozilla.org/en-US/blog/mdn-http-observatory-launch/
- https://developer.mozilla.org/en-US/observatory

**Comment by argl** [comment]
Thank you for raising this, we are aware that this is a missing piece of new observatory and are actively working on documenting this. Feel free to use the mentioned endpoint, this is most probably the one we will be promoting and supporting in the future.

**Comment by chris48s** [comment]
Thanks for letting us know.

**Comment by argl** [comment]
Hi, we just deployed a `/scan` endpoint, returning a reduced set of data, suitable for CI purposes. Documentation is in the [README.md](https://github.com/mdn/mdn-http-observatory/blob/main/README.md#post-apiv2scan)

**Comment by chris48s** [comment]
Great, thanks :+1:
