### ISSUE TITLE
302 Redirects Not Handled

### ISSUE THREAD

**Issue by HDVinnie** [mdn/mdn-http-observatory#53]
### What information was incorrect, unhelpful, or incomplete?

With old site. https://observatory.mozilla.org 

If you scanned for example mysite.com which returns a 302 Redirect to mysite.com/login it would handle that and scan properly. New site now just throws a Error: Site did not respond with a 2xx HTTP status code.

### What did you expect to see?

Scan results

**Comment by caugner** [comment]
@HDVinnie Would you be comfortable sharing the domain you scanned? If you don't want to share it publicly, you can let us know via the comment field in [this feedback survey](https://survey.alchemer.com/s3/7897385/MDN-HTTP-Observatory).

**Comment by HDVinnie** [comment]
> @HDVinnie Would you be comfortable sharing the domain you scanned? If you don't want to share it publicly, you can let us know via the comment field in [this feedback survey](https://survey.alchemer.com/s3/7897385/MDN-HTTP-Observatory).

Done. Pretty sure issue is this line. https://github.com/mdn/mdn-http-observatory/blob/5f7299ef3bff35df4a49e8793d7753d2f7bfe2d3/src/scanner/index.js#L36

**Comment by argl** [comment]
Thank you, we are investigating the issue.

**Comment by argl** [comment]
Could you please check again? Some changes have been deployed.

**Comment by HDVinnie** [comment]
Working perfect now thank you.
