### ISSUE TITLE
SVG sprites, Firefox, and default-src 'none' recommendation

### ISSUE THREAD

**Issue by pepelsbey** [mdn/mdn-http-observatory#6]
I noticed that there’s a questionable recommendation we give in the Observatory:

> Deny by default, using `default-src 'none'`

You can only use SVG sprites via external files in Firefox with `default-src 'self'`

```svg
<svg>
  <use href="/images/icons.svg#icon"/>
</svg>
```

Once you set `default-src 'none'`, your icons will be blocked in Firefox. And you might not notice that because you don’t test in Firefox. Firefox treats external SVG files not as `image-src`, as other browsers do. Currently, no CSP rule would allow Firefox to load this icon, so Firefox defaults to `none` and blocks it.

- [CSP spec issue](https://github.com/w3c/webappsec-csp/issues/199)
- [WONTFIX reply in Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1303364#c4)

I’d change this recommendation or link to the explanation of this specific case documented on MDN.

**Comment by pepelsbey** [comment]
FYI, there’s now [info on MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/default-src#firefox_default-src_none_svg_sprite_blocking_issue) covering this special case in Firefox thanks to @chrisdavidmills

**Comment by caugner** [comment]
![Uploading image.png…]()

**Comment by caugner** [comment]
@pepelsbey As discussed, can you please provide a suggestion for the Recommendation text that takes into consideration this limitation? 🙏

**Comment by mozfreddyb** [comment]
FWIW, while I agree with Jonathan's comment that [`<svg><use>` should not be classified as image loads in Firefox and that it's a huge problem for CSP that there's no clear specification for how they are supposed to be used](https://bugzilla.mozilla.org/show_bug.cgi?id=1303364#c4), I believe that we can fix the compat issue by treating them as images _just for the purpose of CSP loads_. I will not post more comments about the Firefox issue here and would like point you to follow https://bugzilla.mozilla.org/show_bug.cgi?id=1773976 for further updates.

**Comment by argl** [comment]
Since this is a Firefox compat issue tracked on its own entry, I am closing this one.

**Comment by mozfreddyb** [comment]
This should be fixed in Firefox 132, to be released October 29, 2024.
