### ISSUE TITLE
Highest possible score

### ISSUE THREAD

**Issue by craigfrancis** [mdn/mdn-http-observatory#7]
### What information was incorrect, unhelpful, or incomplete?

On the "Tests & Scoring" page, it says "the highest possible score in the HTTP Observatory is currently 135"... that's true of the old system, but it looks like the new one can give at least 145?

### What did you expect to see?

I assume the page content needs tweaking (appreciate the new HTTP Observatory has only just launched).

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/observatory/analyze?host=www.code-poets.co.uk

**Comment by caugner** [comment]
@craigfrancis Good catch, thank you for taking the time to report!

This has also been reported internally, and we have already fixed it via https://github.com/mdn/yari/pull/11407.
