### ISSUE TITLE
Scanning services behind a reverse-proxy with subpath not working

### ISSUE THREAD

**Issue by monsdar** [mdn/mdn-http-observatory#98]
### What information was incorrect, unhelpful, or incomplete?

I'd like to scan web-services I selfhost in my LAN environment. The services run behind a traefik reverse proxy under a subpath. So the URLs to these services are like the following:

* `https://my.domain.com/home`
* `https://my.domain.com/grafana`
* `https://my.domain.com/my_custom_service`

I do not have something running behind `https://my.domain.com`, so when running the scanner I get the following response:

```
# mdn-http-observatory-scan my.domain.com
{"error":"Site did respond with an unexpected HTTP status code 404."}
```

Running with one of the subpath urls looks like this:

```
# mdn-http-observatory-scan https://my.domain.com/my_custom_service
{"error":"The site seems to be down."}
```

...or...

```
# mdn-http-observatory-scan my.domain.com/my_custom_service
{"error":"Site did respond with an unexpected HTTP status code 404."}
```

### What did you expect to see?

I'd like to run the scanner with a specific URL, like so:
* `mdn-http-observatory-scan https://my.domain.com/my_custom_service`

It then should scan that URL for any issues.

### Do you have anything more you want to share?

I'm setting up a local environment using the following commands:

* `docker run -it node:alpine /bin/sh`
* `npm install --global @mdn/mdn-http-observatory`

**Comment by argl** [comment]
Thank you for taking the time to report this issue. While I can understand your concerns and your use case, we currently do not have the ressources to support path-based scanning. It would be a non-trivial refactoring on the server side of things with lots of edge cases.

That said, I will not rule out to support this for the CLI of Observatory in the future, but this is not planned at the moment (PRs certainly welcome).

**Comment by monsdar** [comment]
Understood, thanks for taking your time looking into this
